
export const language = {

  langen:{
      random_poems:'Random Poems',
      random_quotes:'Random Quotes',
      random_jokes:'Random Jokes',
      random_proverbs:'Random Proverbs'

  },
  langfr:{
    random_poems:'Random Poems',
    random_quotes:'Random Quotes',
    random_jokes:'Random Jokes',
    random_proverbs:'Random Proverbs'

  },
  langes:{
    random_poems:'Random Poems',
    random_quotes:'Random Quotes',
    random_jokes:'Random Jokes',
    random_proverbs:'Random Proverbs'

  },
  langht:{
    random_poems:'Random Poems',
    random_quotes:'Random Quotes',
    random_jokes:'Random Jokes',
    random_proverbs:'Random Proverbs',

  },

  rate_english:{
        rating:'Rating',
        title:'Rate Us',
        desc:'If you like the app, please give us 5 Star rating .If you find something wrong, please contact us.',
        feedback:'Feedback'
    },
    rate_spanish:{
        rating:'Clasificación',
        title:'Califique bosotros',
        desc:'Si te gusta la aplicación, por favor danos 5 estrellas. Si encuentras algo mal, ponte en contacto con nosotros',
        feedback:'Reacción'
    },
    rate_french:{
        rating:'Évaluation',
        title:'Évaluez nous',
        desc:"Si vous aimez l'application, donnez-nous une note de 5 étoiles. Si vous trouvez quelque chose qui ne va pas, veuillez nous contacter.",
        feedback:"Retour d'information"
    },
    rate_creole:{
        rating:'Evalyasyon',
        title:'Evalye nou',
        desc:'Si ou renmen aplikasyon an, tanpri ban nou yon Evalyasyon 5 etwal. Si ou jwenn yon bagay ki pa byen mache, tanpri kontakte nou.',
        feedback:'Reyaksyon'
    },
    feedback_english:{
        title:'Feedback',
        picker_title:'Please Choose Feedback Type',
        select_one:'Select One',
        suggestions:'Suggestions',
        bugs:'Bugs',
        questions:'Questions',
        others:'Other',
        button:'Submit',
        subject:'Subject',
        details:'Details'
    },
    feedback_spanish:{
        title:'Realimentación',
        picker_title:'Elija por favor el tipo de la regeneración',
        select_one:'Seleccione uno',
        suggestions:'Sugerencias',
        bugs:'Error',
        questions:'Preguntas',
        others:'Otro',
        button:'Enviar',
        subject:'Tema',
        details:'Detalles'
    },
    feedback_french:{
        title:"Retour d'information",
        picker_title:'Choisissez Type de rétroaction',
        select_one:'Sélectionnez un',
        suggestions:'Suggestions',
        bugs:'Bogues',
        questions:'Questions',
        others:'Autre',
        button:'Soumettre',
        subject:'Sujet',
        details:'Détails'
    },
    feedback_creole:{
        title:'Reyaksyon',
        picker_title:'Tanpri, chwazi yon tip reyaksyon',
        select_one:'Chwazi youn',
        suggestions:'Sijesyon',
        bugs:'Erè',
        questions:'Kesyon',
        others:'Lòt',
        button:'Voye l',
        subject:'Sijè',
        details:'Detay'
    },
    settings_english:{
        title:'Settings',
        default_language:'Default Language',
        english_title:'English',
        spanish_title:'Spanish',
        french_title:'French',
        creole_title:'Creole'
    },
    settings_french:{
        title:'Paramètres',
        default_language:'Langue par défaut',
        english_title:'Anglais',
        spanish_title:'Espagnol',
        french_title:'Français',
        creole_title:"Créole d'Haïti"
    },
    settings_spanish:{
        title:'Configuraciones',
        default_language:'Idioma predeterminado',
        english_title:'Inglés',
        spanish_title:'Español',
        french_title:'Francés',
        creole_title:'Criollo haitiano'
    },
    settings_creole:{
        title:'Paramèt',
        default_language:'Lang pa defo',
        english_title:'Angle',
        spanish_title:'Espayòl',
        french_title:'Fransè',
        creole_title:'Kreyòl'
    },
    common: {
        jokes_title_english: "Jokes",
        jokes_title_spanish: "Bromas",
        jokes_title_french: "Blagues",
        jokes_title_creole: "Blag",
        poems_title_english: "Poems",
        poems_title_spanish: "Poema",
        poems_title_french: "Poems",
        poems_title_creole: "Powèm",
        proverbs_title_english: "Proverbs",
        proverbs_title_spanish: "Proverbios",
        proverbs_title_french: "Proverbes",
        proverbs_title_creole: "Pwovèb",
        quotes_title_english: "Quotes",
        quotes_title_spanish: "Citas",
        quotes_title_french: "Citations",
        quotes_title_creole: "Sitasyon",
        select_english: 'Select',
        select_spanish: 'Seleccionar',
        select_french: 'Sélectionner',
        select_creole: 'Chwazi',
    },
    quotes_english: {
        home:'Home',
        lang:"english",
        api: "APIquotes.php",
        title: "Quotes",
        add_joke_title: "Add Quotes",
        save_title: "Save",
        view_title: "Views",
        rating_title: "Ratings",
        search_title: "Search",
        search_description: "Please enter a search",
        no_record: "No records found ",
        tabTag: "Tags",
        tabThemes: "Themes",
        related_quotes:'Related Quotes',
        share:'Share'
    },
    quotes_spanish: {
        home:'Inicio',
        lang:"spanish",
        api: "APIcitas.php",
        title: "Citas",
        add_joke_title: "Añadir Proverbios",
        save_title: "Guardar",
        view_title: "Puntos de vista",
        rating_title: "Calificaciones",
        search_title: "Buscar",
        search_description: "Ingrese una búsqueda",
        no_record: "No se han encontrado resultados",
        tabTag: "Etiquetas",
        tabThemes: "Temas",
        related_quotes:'Cotizaciones relacionadas',
        share:'Compartir'
    },
    quotes_french: {
        home:'Accueil',
        lang:"french",
        api: "APIcitations.php",
        title: "Citations",
        save_title: "Sauvegarder",
        view_title: "Vues",
        search_description: "Entrez une recherche",
        rating_title: "Évaluations",
        search_title: "Chercher",
        no_record: "Aucun enregistrement trouvé",
        tabTag: "Tags",
        tabThemes: "Thèmes",
        related_quotes:'Citations associées',
        share:'Partager'
    },
    quotes_creole: {
        home:'Kay',
        lang:"creole",
        api: "APIsitasyon.php",
        title: "Sitasyon",
        add_joke_title: "Add Proverb",
        save_title: "Sove",
        view_title: "Opinyon",
        rating_title: "Evalyasyon",
        search_title: "Rechèch",
        search_description: "Tanpri antre yon rechèch",
        no_record: "Pa gen okenn dosye yo te jwenn",
        tabTag: "Etikèt",
        tabThemes: "Tèm",
        related_quotes:'Ki gen rapò Quotes',
        share:'Pataje'
    },
    proverbs_english: {
        home:'Home',
        lang:"english",
        api: "APIproverbs.php",
        title: "Proverbs",
        add_joke_title: "Add Proverb",
        save_title: "Save",
        view_title: "Views",
        rating_title: "Ratings",
        search_title: "Search",
        search_description: "Please enter a search",
        no_record: "No records found ",
        tabTag: "Tags",
        tabThemes: "Themes",
        related:'Related Proverbs',
        share:'Share'
    },
    proverbs_spanish: {
        home:'Inicio',
        lang:"spanish",
        api: "APIproverbios.php",
        title:'Proverbios',
        add_joke_title: "Añadir un proverbio",
        save_title: "Guardar",
        view_title: "Puntos de vista",
        rating_title: "Calificaciones",
        search_title: "Buscar",
        search_description: "Ingrese una búsqueda",
        no_record: "No se han encontrado resultados",
        tabTag: "Etiquetas",
        tabThemes: "Temas",
        related:'Proverbios similares',
        share:'Compartir'
    },
    proverbs_french: {
        home:'Accueil',
        lang:"french",
        api: "APIproverbes.php",
        title: "Proverbes",
        save_title: "Sauvegarder",
        view_title: "Vues",
        search_description: "Entrez une recherche",
        rating_title: "Évaluations",
        search_title: "Chercher",
        no_record: "Aucun enregistrement trouvé",
        tabTag: "Tags",
        tabThemes: "Thèmes",
        related:'Proverbes liés',
        share:'Partager'
    },
    proverbs_creole: {
        home:'Kay',
        lang:"creole",
        api: "APIpwoveb.php",
        title: "Pwoveb",
        add_joke_title: "Add Proverb",
        save_title: "Sove",
        view_title: "Opinyon",
        rating_title: "Evalyasyon",
        search_title: "Rechèch",
        search_description: "Tanpri antre yon rechèch",
        no_record: "Pa gen okenn dosye yo te jwenn",
        tabTag: "Etikèt",
        tabThemes: "Tèm",
        related:'Pwovèb ki gen rapò',
        share:'Pataje'
    },
    jokes_english: {
        home:'Home',
        lang:'english',
        api: "APIjokes.php",
        title: "Jokes",
        add_joke_title: "Add Joke",
        save_title: "Save",
        view_title: "Views",
        rating_title: "Ratings",
        search_title: "Search",
        search_description: "Please enter a search",
        no_record: "No records found ",
        tabTag: "Tags",
        tabThemes: "Themes",
        field_author_name:'Author',
        field_email:'Email',
        field_title:'Title',
        field_keywords:'Keywords',
        field_text:'Jokes',
        field_select_category:'Select a category',
        done:'Done',
        related:'Related Jokes',
        share:'Share'

    },
    jokes_spanish: {
        home:'Inicio',
        lang:'spanish',
        api: "APIbromas.php",
        title: "Bromas",
        add_joke_title: "Añadir broma",
        save_title: "Guardar",
        view_title: "Puntos de vista",
        rating_title: "Calificaciones",
        search_title: "Buscar",
        search_description: "Ingrese una búsqueda",
        no_record: "No se han encontrado resultados",
        tabTag: "Etiquetas",
        tabThemes: "Temas",
        field_author_name:'Autor',
        field_email:'Email',
        field_title:'Título',
        field_keywords:'Palabras claves',
        field_text:'Bromas',
        field_select_category:'Seleccione una categoría',
        done:'Hecho',
        related:'Bromas similares',
        share:'Compartir'
    },
    jokes_french: {
        home:'Accueil',
        lang:'french',
        api: "APIblagues.php",
        title: "Blagues",
        add_joke_title: "Ajouter une blague",
        save_title: "Sauvegarder",
        view_title: "Vues",
        search_description: "Entrer une recherche",
        rating_title: "Évaluations",
        search_title: "Chercher",
        no_record: "Aucun résultat trouvé",
        tabTag: "Tags",
        tabThemes: "Thèmes",
        field_author_name:'Auteur',
        field_email:'Email',
        field_title:'Titre',
        field_keywords:'Mots clés',
        field_text:'Blague',
        field_select_category:'Choisir une catégorie',
        done:'Terminé',
        related:'Blagues similaire',
        share:'Partager'

    },
    jokes_creole: {
        home:'Akèy',
        lang:'creole',
        api: "APIblag.php",
        title: "Blag",
        add_joke_title: "Ajoute yon blag",
        save_title: "Anrejistre",
        view_title: "Vizit",
        rating_title: "Evalyasyon",
        search_title: "Rechèch",
        search_description: "Tanpri antre kèk mo kle",
        no_record: "Nou pa jwenn okenn rezilta",
        tabTag: "Mo kle",
        tabThemes: "Tèm",
        field_author_name:'Otè',
        field_email:'Imèl',
        field_title:'Tit',
        field_keywords:'Mo kle',
        field_text:'Blag',
        field_select_category:'Chwazi yon kategori',
        done:'Fini',
        related:'Nan menm kategori a',
        share:'Pataje'
    },
    english: {
        home:'Home',
        lang:'english',
        title: "Poems",
        add_poem_title: "Add Poem",
        save_title: "Save",
        search_title: "Search",
        search_description: "Enter some keywords",
        view_title: "View",
        rating_title: "Ratings",
        tabPoem: "Poems",
        tabTag: "Tags",
        tabThemes: "Themes",
        no_record: "No records found ",
        poemUrl: "APIpoems.php",
        field_author_name:'Author',
        field_email:'Email',
        field_title:'Title',
        field_keywords:'Keywords',
        field_text:'Poem',
        field_select_category:'Select a category',
        done:'Done',
        related:'Related Poems',
        share:'Share'
    },
    spanish: {
        home:'Inicio',
        lang:'spanish',
        title: "Poema",
        add_poem_title: "Añadir un poema",
        save_title: "Guardar",
        search_title: "Buscar",
        search_description: "Ingrese algunas palabras clave",
        view_title: "Vistas",
        rating_title: "Calificaciones",
        tabPoem: "Poema",
        tabTag: "Etiqueta",
        tabThemes: "Tema",
        no_record: "No se han encontrado resultados",
        poemUrl: "APIpoemas.php",
        field_author_name:'Autor',
        field_email:'Email',
        field_title:'Título',
        field_keywords:'Palabras claves',
        field_text:'Poema',
        field_select_category:'Seleccione una categoría',
        done:'Hecho',
        related:'Poemas similares',
        share:'Compartir'
    },
    french: {
        home:'Accueil',
        lang:'french',
        title: "Poèmes",
        add_poem_title: "Ajouter un poème",
        save_title: "Sauvegarder",
        search_title: "Chercher",
        search_description: "Entrez une recherche",
        view_title: "Vues",
        rating_title: "Évaluations",
        tabPoem: "Poèmes",
        tabTag: "Mots clés",
        tabThemes: "Thèmes",
        no_record: "Aucun enregistrement trouvé",
        poemUrl: "APIpoemes.php",
        field_author_name:'Auteur',
        field_email:'Email',
        field_title:'Titre',
        field_keywords:'Mots clés',
        field_text:'Poème',
        field_select_category:'Choisir une catégorie',
        done:'Terminé',
        related:'Poèmes liés',
        share:'Partager'
    },
    creole: {
        home:'Akèy',
        lang:'creole',
        title: "Powèm",
        add_poem_title: "Ajoute Powèm",
        save_title: "Anrejistre",
        view_title: "Vizit",
        rating_title: "Evalyasyon",
        search_title: "Rechèch",
        search_description: "Tanpri antre yon rechèch",
        tabPoem: "Powèm",
        tabTag: "Mo kle",
        tabThemes: "Tèm",
        no_record: "Dezole, nou pa jwenn okenn rezilta",
        poemUrl: "APIpowem.php",
        field_author_name:'Otè',
        field_email:'Imèl',
        field_title:'Tit',
        field_keywords:'Mo kle',
        field_text:'Powèm',
        field_select_category:'Chwazi yon kategori',
        done:'Fini',
        related:'Nan menm kategori a',
        share:'Pataje'
    }
}
